@baseUrl = https://intit.cognitiveservices.azure.com
@baseHasseUrl = https://ai102testaiazureaiservice.cognitiveservices.azure.com

@key = 0ac5.....

@token = eyJ0...

###

POST {{baseHasseUrl}}/text/analytics/v3.0/languages
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "documents" : [
        {
            "id" : "1",
            "text" : "Hej med jer"
        },
        {
            "id" : "2",
            "text" : "This is an Azure course"
        },
        {
            "id" : "3",
            "text" : "Jak się masz"
        }
    ]
}

###

POST {{baseUrl}}/translator/text/v3.0/translate?to=EN
Ocp-apim-subscription-key: {{key}}

[
    {
        "text" : "Hej med jer"
    }
]


###
POST {{baseUrl}}/contentmoderator/moderate/v1.0/ProcessText/Screen?autocorrect=true
Ocp-apim-subscription-key: {{key}}
Content-Type: text/plain

This is text, go fuck yourself, my email is lacour@gmail.com