@baseUrl = https://ai102mlcservice1.cognitiveservices.azure.com/
@baseHasseUrl = https://ai102testaiazureaiservice.cognitiveservices.azure.com

@key = d76276d90b774b71a5482d1c29ec8c81

@token = eyJ0...

###

POST {{baseHasseUrl}}/text/analytics/v3.0/languages
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "documents" : [
        {
            "id" : "1",
            "text" : "Hej med jer"
        },
        {
            "id" : "2",
            "text" : "This is an Azure course"
        },
        {
            "id" : "3",
            "text" : "Jak się masz"
        }
    ]
}

###

POST {{baseUrl}}/translator/text/v3.0/translate?to=EN
Ocp-apim-subscription-key: {{key}}

[
    {
        "text" : "Hej med jer"
    }
]


###
POST {{baseUrl}}/contentmoderator/moderate/v1.0/ProcessText/Screen?autocorrect=true
Ocp-apim-subscription-key: {{key}}
Content-Type: text/plain

This is text, go fuck yourself, my email is lacour@gmail.com


### 
POST {{baseUrl}}/vision/v3.2/describe
Ocp-apim-subscription-key: {{key}}

{"url":"https://media.cntraveler.com/photos/58de89946c3567139f9b6cca/16:9/w_2560%2Cc_limit/GettyImages-468366251.jpg"}


###

POST {{baseUrl}}/computervision/imageanalysis:analyze
Ocp-apim-subscription-key: {{key}}

{"url":"https://www.cowgirlmagazine.com/wp-content/uploads/2020/02/19/Elvis.jpg"}


###

GET https://ai102mlcservice1.cognitiveservices.azure.com/vision/v3.2/read/analyzeResults/7cca6fed-527d-4dd1-b7d4-a726f0c88924
Ocp-apim-subscription-key: {{key}}