@key = cc...

@baseUrl = https://ai102mlcdemo02.cognitiveservices.azure.com


### Read image text

POST {{baseUrl}}/vision/v3.2/read/analyze
Ocp-apim-subscription-key: {{key}}

{
    "url" : "https://ai102mlcdemo1.blob.core.windows.net/myprivatecontainer/mortenstext.png"
}


### GET response (when ready)

GET https://ai102mlcdemo02.cognitiveservices.azure.com/vision/v3.2/read/analyzeResults/e91fb129-f481-4eff-86dc-64da88d59dbe
Ocp-apim-subscription-key: {{key}}